import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { lovable } from "@/integrations/lovable";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SiteShell } from "@/components/site-shell";

export const Route = createFileRoute("/auth")({ head:()=>({meta:[{title:"Admin sign in — JH Digitals"},{name:"description",content:"Secure JH Digitals administration sign in."},{property:"og:title",content:"Admin sign in — JH Digitals"},{property:"og:description",content:"Secure JH Digitals administration sign in."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}), component: AuthPage });
function AuthPage(){ const navigate=useNavigate(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [message,setMessage]=useState(""); async function signIn(){setMessage("Signing in…"); const {error}=await supabase.auth.signInWithPassword({email,password}); if(error){setMessage(error.message);return;} navigate({to:"/admin"});} async function google(){const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin}); if(result.error)setMessage(result.error.message);} return <SiteShell><main className="grid min-h-screen place-items-center px-5 pt-20"><div className="w-full max-w-md border border-primary-foreground/10 bg-panel p-7"><p className="font-mono text-[10px] uppercase text-accent">Restricted access</p><h1 className="mt-3 font-display text-3xl uppercase">Admin sign in</h1><div className="mt-8 space-y-4"><Input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email" className="border-primary-foreground/15 bg-primary text-primary-foreground"/><Input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password" className="border-primary-foreground/15 bg-primary text-primary-foreground"/><Button className="w-full" variant="dock" onClick={signIn}>Sign in</Button><Button className="w-full border-primary-foreground/20 text-primary-foreground hover:bg-primary-foreground hover:text-primary" variant="outline" onClick={google}>Continue with Google</Button>{message&&<p role="status" className="text-sm text-muted-foreground">{message}</p>}</div></div></main></SiteShell>}