import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Check } from "lucide-react";
import { SiteFooter, SiteShell } from "@/components/site-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { submitInquiry } from "@/lib/content";

export const Route=createFileRoute("/start-project")({head:()=>({meta:[{title:"Start a project — JH Digitals"},{name:"description",content:"Tell JH Digitals about your product, website, or platform."},{property:"og:title",content:"Start a project — JH Digitals"},{property:"og:description",content:"Begin a digital product project with JH Digitals."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:StartProject});
function StartProject(){const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{await submitInquiry({data:{name:String(f.get("name")),email:String(f.get("email")),company:String(f.get("company")||""),budget:String(f.get("budget")),timeline:String(f.get("timeline")),brief:String(f.get("brief"))}});setSent(true)}catch(err){setError(err instanceof Error?err.message:"Please try again.")}finally{setBusy(false)}}return <SiteShell><main className="dark-grid px-5 pb-24 pt-36 md:px-10"><div className="mx-auto grid max-w-[1200px] gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono text-[10px] uppercase text-accent">New project / 01</p><h1 className="mt-5 font-display text-5xl font-bold uppercase leading-none md:text-7xl">Build something useful.</h1><p className="mt-7 max-w-md leading-7 text-muted-foreground">Tell us where you are, where you want to go, and what success should look like.</p><a href="mailto:jhdigitals1@gmail.com" className="mt-10 inline-block text-accent">jhdigitals1@gmail.com</a></div>{sent?<div className="grid min-h-96 place-items-center border border-primary-foreground/10 bg-panel p-8 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-full bg-success-soft text-success"><Check/></span><h2 className="mt-5 font-display text-3xl uppercase">Brief received</h2><p className="mt-3 text-muted-foreground">We’ll review your project and reply by email.</p></div></div>:<form onSubmit={submit} className="grid gap-5 border border-primary-foreground/10 bg-panel p-6 md:grid-cols-2 md:p-10">{[["name","Your name","text"],["email","Email address","email"],["company","Company (optional)","text"],["budget","Budget range","text"],["timeline","Preferred timeline","text"]].map(([name,placeholder,type])=><Input key={name} name={name} type={type} required={name!=="company"} placeholder={placeholder} className="border-primary-foreground/15 bg-primary text-primary-foreground placeholder:text-muted-foreground"/>)}<Textarea name="brief" required minLength={20} placeholder="Describe the project, goals, and what you need from us." className="min-h-44 border-primary-foreground/15 bg-primary text-primary-foreground placeholder:text-muted-foreground md:col-span-2"/><Button disabled={busy} variant="dock" className="md:col-span-2">{busy?"Sending…":"Submit project brief"}</Button>{error&&<p role="alert" className="text-sm text-destructive md:col-span-2">{error}</p>}</form>}</div></main><SiteFooter/></SiteShell>}